<h3><?php echo __('Quick Stats'); ?></h3>

<!-- Button -->
<div class="btn-box">
<div class="btn-top"></div>
<div class="btn">
	<dl>
		<dt><a href="<?php echo URL::site('/project/'.$project->id.'/stream');?>"><?php echo __('Stream');?></a> (<?php echo $items; ?>)</dt>
		<dd><?php echo __('Items generated by this project');?></dd>
	</dl>
</div> <!-- /btn -->
<div class="btn-bottom"></div>
</div> <!-- /btn-box -->

<!-- Button -->
<div class="btn-box">
<div class="btn-top"></div>
<div class="btn">
	<dl>
		<dt><a href="<?php echo URL::site('/project/'.$project->id.'/stories');?>"><?php echo __('Stories');?></a> (<?php echo $stories; ?>)</dt>
		<dd><?php echo __('Stories created in this project');?></dd>
	</dl>
</div> <!-- /btn -->
<div class="btn-bottom"></div>
</div> <!-- /btn-box -->

<!-- Button -->
<div class="btn-box">
<div class="btn-top"></div>
<div class="btn">
	<dl>
		<dt><a href="#"><?php echo __('Tags');?></a> (<?php echo $tags; ?>)</dt>
		<dd><?php echo __('Tags generated by this project');?></dd>
	</dl>
</div> <!-- /btn -->
<div class="btn-bottom"></div>
</div> <!-- /btn-box -->

<!-- Button -->
<div class="btn-box">
<div class="btn-top"></div>
<div class="btn">
	<dl>
		<dt><a href="#"><?php echo __('Links');?></a> (<?php echo $links; ?>)</dt>
		<dd><?php echo __('Links generated by this project');?></dd>
	</dl>
</div> <!-- /btn -->
<div class="btn-bottom"></div>
</div> <!-- /btn-box -->

<!-- Button -->
<div class="btn-box">
<div class="btn-top"></div>
<div class="btn">
	<dl>
		<dt><a href="#"><?php echo __('Places');?></a> (<?php echo $places; ?>)</dt>
		<dd><?php echo __('Places generated by this project');?></dd>
	</dl>
</div> <!-- /btn -->
<div class="btn-bottom"></div>
</div> <!-- /btn-box -->

<!-- Button -->
<div class="btn-box">
<div class="btn-top"></div>
<div class="btn">
	<dl>
		<dt><a href="<?php echo URL::site('/project/'.$project->id.'/builder');?>"><?php echo __('Feeds');?></a> (<?php echo $feeds; ?>)</dt>
		<dd><?php echo __('Feeds that generate items for the stream');?></dd>
	</dl>
</div> <!-- /btn -->
<div class="btn-bottom"></div>
</div> <!-- /btn-box -->

<?php
// Sweeper Plugin Hook -- add button
Event::run('sweeper.project.stats.button');
?>

<div class="fix"></div>


<p></p>

<div id="charts"></div>